-- AlterTable
ALTER TABLE `bookings` MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'CONFIRMEE', 'CHECKIN_CLIENT', 'CHECKIN_PROPRIO', 'EN_COURS_SEJOUR', 'TERMINEE') NOT NULL DEFAULT 'PENDING';
